version: '3'

services:

  api-gateway:
    build:
      context: api-gateway
      args:
        BUILDTIME_ORDER_HOST: 172.28.1.6
        BUILDTIME_INFO_HOST: 172.28.1.7
    ports:
      - "3000:3000"
    networks:
      backend:
        ipv4_address: 172.28.1.5

  order:
    build:
      context: order
      args:
        BUILDTIME_DB_DATABASE: ${DB_DATABASE}
        BUILDTIME_DB_HOST: ${DB_HOST}
        BUILDTIME_DB_PORT: ${DB_PORT}
        BUILDTIME_DB_USERNAME: ${DB_USERNAME}
        BUILDTIME_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.28.1.6

  info:
    build:
      context: info
      args:
        BUILDTIME_DB_DATABASE: ${DB_DATABASE}
        BUILDTIME_DB_HOST: ${DB_HOST}
        BUILDTIME_DB_PORT: ${DB_PORT}
        BUILDTIME_DB_USERNAME: ${DB_USERNAME}
        BUILDTIME_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.28.1.7

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16