apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-info
  labels:
    app: info-service
spec:
  replicas: 3  # Modify replicas according to your case
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
      - name: info-service-container
        image: heyyytamvo/eks:info-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: info-service
  labels:
    app: info-service
spec:
  type: NodePort
  selector:
    app: info-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP