apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-order
  labels:
    app: order-service
spec:
  replicas: 3  # Modify replicas according to your case
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: heyyytamvo/eks:order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP