version: '3'

services:

  api-gateway:
    build:
      context: api-gateway
    ports:
      - "3000:3000"
    networks:
      - backend

  order:
    build:
      context: order
      args:
        BUILDTIME_DB_DATABASE: ${DB_DATABASE}
        BUILDTIME_DB_HOST: ${DB_HOST}
        BUILDTIME_DB_PORT: ${DB_PORT}
        BUILDTIME_DB_USERNAME: ${DB_USERNAME}
        BUILDTIME_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3001:3001"
    networks:
      - backend

  info:
    build:
      context: info
      args:
        BUILDTIME_DB_DATABASE: ${DB_DATABASE}
        BUILDTIME_DB_HOST: ${DB_HOST}
        BUILDTIME_DB_PORT: ${DB_PORT}
        BUILDTIME_DB_USERNAME: ${DB_USERNAME}
        BUILDTIME_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3002:3002"
    networks:
      - backend

networks:
  backend:
    driver: bridge